site_name: "dinarasaurae's webdev"
theme:
  name: 'material'
  palette:
    primary: 'orange'
    accent: 'red'

nav:
  - Home: index.md
  - LAB №1:
    - ERD: lab1/erd.md
    - Task 1: lab1/task1.md
    - Task 2: lab1/task2.md
    - Task 3: lab1/task3.md
    - Psychologists Service: lab1/service.md
  - LAB №2:
    - Data model: lab2/data.md
    - Registration: lab2/registration.md
    - Authorization: lab2/authorization.md
    - Dashboard: lab2/dashboard.md
    - Menu: lab2/menu.md
    - Search: lab2/search.md
    - Submission: lab2/submission.md
    - Homework: lab2/homeworks.md

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.details